namespace Workflow.Visual;

/// <summary>
/// Represents the complete diagram model extracted from a workflow class.
/// </summary>
public class WorkflowDiagramModel
{
    public string WorkflowName { get; init; } = "";
    public string InputType { get; init; } = "";
    public string StateType { get; init; } = "";
    public string OutputType { get; init; } = "";

    public List<StateTransition> StateTransitions { get; init; } = [];
    public List<DecisionRule> DecisionRules { get; init; } = [];
}

/// <summary>
/// Represents a state transition from InternalEvolve method.
/// Pattern: (FromState, Event{Message: InputType}) => ToState
/// </summary>
public record StateTransition(
    string FromState,
    string EventType,      // InitiatedBy, Received, etc.
    string InputType,      // The message type that triggers the transition
    string ToState
);

/// <summary>
/// Represents a decision rule from Decide method.
/// Pattern: (InputType, State) => Commands[]
/// </summary>
public record DecisionRule(
    string InputType,
    string StateType,
    List<CommandInfo> Commands
);

/// <summary>
/// Represents a command generated by the Decide method.
/// </summary>
public record CommandInfo(
    CommandKind Kind,
    string MessageType,
    string Details = ""    // Optional: delay for Schedule, etc.
);

/// <summary>
/// The kind of workflow command.
/// </summary>
public enum CommandKind
{
    Send,
    Publish,
    Schedule,
    Reply,
    Complete
}
